"""Preset catalog for major LLM runners (cloud gallery quick-add).

Each preset pre-fills the provider form: kind, base URL, default model,
capability flags, and where to get an API key. Model names are defaults the
user can change; nothing here is hard-coded into call paths.
"""

PRESETS = [
    {
        "id": "openai",
        "name": "OpenAI",
        "kind": "openai_compatible",
        "base_url": "https://api.openai.com/v1",
        "default_model": "gpt-4o-mini",
        "key_url": "https://platform.openai.com/api-keys",
        "is_local": False,
        "vision": True,
        "json_schema": True,
        "json_object": True,
        "context_window": 128000,
        "extra_headers": {},
        "notes": "Structured output supported. Billed per token.",
    },
    {
        "id": "anthropic",
        "name": "Anthropic (Claude)",
        "kind": "anthropic",
        "base_url": "https://api.anthropic.com",
        "default_model": "claude-sonnet-4-20250514",
        "key_url": "https://console.anthropic.com/settings/keys",
        "is_local": False,
        "vision": True,
        "json_schema": False,
        "json_object": False,
        "context_window": 200000,
        "extra_headers": {},
        "notes": "Prompt-only JSON (validated downstream). Billed per token.",
    },
    {
        "id": "openrouter",
        "name": "OpenRouter",
        "kind": "openai_compatible",
        "base_url": "https://openrouter.ai/api/v1",
        "default_model": "anthropic/claude-sonnet-4",
        "key_url": "https://openrouter.ai/keys",
        "is_local": False,
        "vision": True,
        "json_schema": True,
        "json_object": True,
        "context_window": 200000,
        "extra_headers": {
            "HTTP-Referer": "https://github.com/AkashPanja/Action-Bridge",
            "X-Title": "Action Bridge",
        },
        "notes": "One key for 100+ models. Use vendor/model slugs as the model name.",
    },
    {
        "id": "deepseek",
        "name": "DeepSeek",
        "kind": "openai_compatible",
        "base_url": "https://api.deepseek.com/v1",
        "default_model": "deepseek-chat",
        "key_url": "https://platform.deepseek.com/api_keys",
        "is_local": False,
        "vision": False,
        "json_schema": True,
        "json_object": True,
        "context_window": 64000,
        "extra_headers": {},
        "notes": "Cheap chat models. deepseek-reasoner thinks longer (slower).",
    },
    {
        "id": "groq",
        "name": "Groq",
        "kind": "openai_compatible",
        "base_url": "https://api.groq.com/openai/v1",
        "default_model": "llama-3.3-70b-versatile",
        "key_url": "https://console.groq.com/keys",
        "is_local": False,
        "vision": True,
        "json_schema": True,
        "json_object": True,
        "context_window": 128000,
        "extra_headers": {},
        "notes": "Very fast inference. Generous free tier.",
    },
    {
        "id": "mistral",
        "name": "Mistral",
        "kind": "openai_compatible",
        "base_url": "https://api.mistral.ai/v1",
        "default_model": "mistral-small-latest",
        "key_url": "https://console.mistral.ai/api-keys",
        "is_local": False,
        "vision": True,
        "json_schema": True,
        "json_object": True,
        "context_window": 128000,
        "extra_headers": {},
        "notes": "EU-hosted option. Native JSON mode supported.",
    },
    {
        "id": "together",
        "name": "Together AI",
        "kind": "openai_compatible",
        "base_url": "https://api.together.xyz/v1",
        "default_model": "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        "key_url": "https://api.together.ai/settings/api-keys",
        "is_local": False,
        "vision": True,
        "json_schema": True,
        "json_object": True,
        "context_window": 128000,
        "extra_headers": {},
        "notes": "Wide open-model catalog, vendor/model slugs.",
    },
    {
        "id": "fireworks",
        "name": "Fireworks AI",
        "kind": "openai_compatible",
        "base_url": "https://api.fireworks.ai/inference/v1",
        "default_model": "accounts/fireworks/models/llama-v3p3-70b-instruct",
        "key_url": "https://fireworks.ai/api-keys",
        "is_local": False,
        "vision": True,
        "json_schema": True,
        "json_object": True,
        "context_window": 128000,
        "extra_headers": {},
        "notes": "Fast open-model inference with response_format support.",
    },
    {
        "id": "xai",
        "name": "xAI (Grok)",
        "kind": "openai_compatible",
        "base_url": "https://api.x.ai/v1",
        "default_model": "grok-3-mini",
        "key_url": "https://console.x.ai/",
        "is_local": False,
        "vision": True,
        "json_schema": True,
        "json_object": True,
        "context_window": 131072,
        "extra_headers": {},
        "notes": "OpenAI-compatible chat completions.",
    },
    {
        "id": "gemini",
        "name": "Google Gemini",
        "kind": "openai_compatible",
        "base_url": "https://generativelanguage.googleapis.com/v1beta/openai",
        "default_model": "gemini-2.0-flash",
        "key_url": "https://aistudio.google.com/apikey",
        "is_local": False,
        "vision": True,
        "json_schema": False,
        "json_object": True,
        "context_window": 1000000,
        "extra_headers": {},
        "notes": "Uses Gemini's OpenAI-compatibility endpoint. Huge context, cheap.",
    },
    {
        "id": "ollama-remote",
        "name": "Ollama (remote)",
        "kind": "openai_compatible",
        "base_url": "http://192.168.1.10:11434/v1",
        "default_model": "qwen2.5:3b",
        "key_url": "",
        "is_local": False,
        "vision": False,
        "json_schema": False,
        "json_object": True,
        "context_window": 8192,
        "extra_headers": {},
        "notes": "Point at any Ollama server on your network. Edit the IP. No key needed.",
    },
    {
        "id": "vllm",
        "name": "vLLM server",
        "kind": "openai_compatible",
        "base_url": "http://localhost:8001/v1",
        "default_model": "meta-llama/Llama-3.1-8B-Instruct",
        "key_url": "",
        "is_local": True,
        "vision": False,
        "json_schema": True,
        "json_object": True,
        "context_window": 32768,
        "extra_headers": {},
        "notes": "Self-hosted OpenAI-compatible server (vllm serve ...). Mark local if on this machine.",
    },
    {
        "id": "lmstudio",
        "name": "LM Studio",
        "kind": "openai_compatible",
        "base_url": "http://localhost:1234/v1",
        "default_model": "local-model",
        "key_url": "",
        "is_local": True,
        "vision": False,
        "json_schema": False,
        "json_object": True,
        "context_window": 8192,
        "extra_headers": {},
        "notes": "Desktop runner. Start the server in LM Studio, replace the model id.",
    },
]


def list_presets() -> list[dict]:
    return [dict(p) for p in PRESETS]


def get_preset(preset_id: str) -> dict | None:
    for preset in PRESETS:
        if preset["id"] == preset_id:
            return dict(preset)
    return None
